version: '2'
services:
  graphite:
    image: hopsoft/graphite-statsd
    restart: always
    container_name: graphite
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125"
      - "8126:8126"
